### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by Fenicu** [danilsolo/ww_robot#2]
Стамину считает как арену, или поменять надо значёк на бутылку или пофиксить арену, но думаю было бы логичнее таки поставить арену, ибо стамина не нужна в отчёте, разве только что общее количество..
так же салфетку надо обновить, там старая.
ещё есть мысль о том, что каждый член отряда будет кидать в бота свою промо ссылку и донат ссылку.
Донат ссылку можно для подарков использовать, а промо логично если звать кого нибудь 1.. иначе можно за накрутку схватить бан

**Comment by Fenicu** [comment]
вот новая салфетка

‼️ Режим тишины! ‼️
 Ходок! Приготовься к атаке (⚔️ Атака) до 'Смелый Вояка, Выбирай врага!'

 Если ты вдруг любишь перед боем переодеваться, тебе могут помочь следующие команды. Отправь это сообщение (FORWARD) боту и жми то, что надо надеть:
 ⚔️ Оружие:
 Нарсил /on_124
 Экскалибур /on_115
 Меч берсеркера /on_107
 Рапира /on_106
 --
 Кинжал триумфа /on_126
 Кинжал демона /on_118
 Кинжал охотника /on_117
 Кинжал: /on_114
 --
 Деф:
 Эльфийское копье /on_110
 Мифриловый щит: /on_216

 Ходоки не плюсуют в чат!!
 (хэштег #салфетка)
 ‼️ Режим тишины! ‼️

**Comment by danilsolo** [comment]
done
